version: '3.0'

services:
  testimonials_dv_dev:
    image: mysql:5.7
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - '3412:3306'
    environment:
      MYSQL_DATABASE: testimonials_dv_prod
      MYSQL_ROOT_USER: juandevsigner
      MYSQL_USER: juandevsigner
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret

  api:
    build: .
    container_name: api_container_crud
    ports:
      - '5700:5700'
    depends_on:
      - testimonials_dv_dev
    restart: on-failure
